language: java
env:
	global:
		- GPG_DIR="`pwd`/deploy"
jdk:
	- oraclejdk8
script:
	- mvn clean test jacoco:report -P continous-integration
after_success:
	- mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$PROJECT_TOKEN -DapiToken=$API_TOKEN
before_deploy:
	- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
	- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
deploy:
	- mvn deploy --settings deploy/settings.xml -DperformRelease=true -DskipTests=true


